version: '3'

services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_NAME:-ParkHereDb}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - parkhere-2025

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ__USERNAME:-guest}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ__PASSWORD:-guest}
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - 5672
    networks:
      - parkhere-2025

  parkhere-rabbitmq:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.notifications
    environment:
      - RABBITMQ_HOST=${RABBITMQ__HOST:-rabbitmq}
      - RABBITMQ_USERNAME=${RABBITMQ__USERNAME:-guest}
      - RABBITMQ_PASSWORD=${RABBITMQ__PASSWORD:-guest}
      - RABBITMQ_VIRTUALHOST=/
    depends_on:
      - rabbitmq
      - postgres
      - parkhere-api
    networks:
      - parkhere-2025
    ports:
      - 7111:80

  parkhere-api:
    build:
      context: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_MODE=local
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=${DB_NAME:-ParkHereDb}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD}
      - RABBITMQ__HOST=rabbitmq
      - RABBITMQ__USERNAME=${RABBITMQ__USERNAME:-guest}
      - RABBITMQ__PASSWORD=${RABBITMQ__PASSWORD:-guest}
      - RABBITMQ__VIRTUALHOST=/
      - TZ=Europe/Sarajevo
    ports:
      - "5130:5130"
    networks:
      - parkhere-2025
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  parkhere-2025:
    driver: bridge